name: Upload Podcast Episode

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install feedparser moviepy google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run upload script
        env:
          YOUTUBE_TOKEN_JSON: ${{ secrets.YOUTUBE_TOKEN_JSON }}
        run: |
          echo "$YOUTUBE_TOKEN_JSON" > token.json
          python upload_from_rss.py
