name: انتشار خودکار پادکست

on:
  schedule:
    - cron: '20 20 * * *'  # هر روز ساعت 23:20 به وقت استانبول
  workflow_dispatch:


jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت فایل‌ها از مخزن
        uses: actions/checkout@v3

      - name: نصب ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: نصب پایتون
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: نصب کتابخانه‌ها
        run: |
          pip install --upgrade pip
          pip install pillow==9.5.0
          pip install beautifulsoup4
          pip install moviepy==1.0.3 imageio imageio-ffmpeg numpy decorator proglog feedparser google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: اجرای اسکریپت
        env:
          YOUTUBE_TOKEN_JSON: ${{ secrets.YOUTUBE_TOKEN_JSON }}
        run: |
          echo "$YOUTUBE_TOKEN_JSON" > token.json
          python upload_from_rss.py
